aws/aws-sdk-net-extensions-cognito

- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
Noticed I had a gap in the "forgot password workflow", this is filling the gap:
This is needed because the client secret is only accessible through the userpool class (private property).
> ConfirmForgotPassword implementation with pool secret hash

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoDeviceHelper.cs
*Issue #, if available:* DOTNET-3206
*Description of changes:* Using a cryptographic random number (System.Security.Cryptography.RandomNumberGenerator) generator instead of the Random class 
> Using a cryptographic random number generator

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
*Issue #, if available:* DOTNET-3350
Fixes https://github.com/aws/aws-sdk-net/issues/1129
There was a missing parameter when resetting password. 
Tested with my personal account, fixes the bug
> Allowing optional attributes when responding to change password challenge

- test/Amazon.Extensions.CognitoAuthentication.UnitTests/AuthenticationCryptoTests.cs
Unit test fails in AWS CodeBuild
Change generation of time string (dependent on time zone) to a hard-coded value.
> Update test to be timezone agnostic.

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
None
To allow usage of AWSSDKs with version less than equal to 4.0.
> Update AWS SDK package references upper bound to 4.0

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
Updating version numbers to 1.0.4 for release to NuGet. This release prepares for the AWS SDK for .NET v3.5 release.
> Update version numbers for 1.0.4

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
Fixes https://github.com/aws/aws-sdk-net-extensions-cognito/issues/22
*Issue #, if available:* https://github.com/aws/aws-sdk-net-extensions-cognito/issues/22
Reloads the RefreshToken from initial request since service does not return back the RefreshToken for `refresh_token` auth flow.
---
> Fixes an issue where RefreshToken is lost when executing StartWithRefreshTokenAuthAsync

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/Util/AuthenticationHelper.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
Fix Device level auth region in StartWithSRPAuth in order to avoid error
"Device Group Key and Device Pass required for authentication."
for requests without a device
Also fix invalid username or password issue with providing device information in StartWithSRPAuth
> Fix Device level auth issue

- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
*Issue #, if available:
https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/151
Mock testing `CognitoUser` using [Moq](https://github.com/moq/moq4) fails because it needs virtual methods to create a proxy with [[1](https://github.com/moq/moq4/issues/212)]. 
Currently the workaround is to write a subclass to wrap around the CognitoUser class as follows
```csharp
public class CustomCognitoUser : CognitoUser
{
public CustomCognitoUser(string userID, string clientID, CognitoUserPool pool, IAmazonCognitoIdentityProvider provider, string? clientSecret = null, string? status = null, string? username = null, Dictionary<string, string>? attributes = null) : base(userID, clientID, pool, provider, clientSecret, status, username, attributes)
{
}
public virtual …
```
> Virtual methods for CognitoUser

- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserSession.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/BaseAuthenticationTestClass.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/MfaAuthenticationTests.cs
https://github.com/aws/aws-sdk-net-extensions-cognito/issues/69#issuecomment-819463129
Replace all uses of `DateTime.Now` with `DateTime.UtcNow`.
The **CognitoUser.cs** class had incorrect line endings which is why it is showing a full file change. I committed it this way to get the file fixed up for going forward. There was one actual file change on line 483 to change to UtcNow.
> Switch all calls from DateTime.Now to DateTime.UtcNow

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserSession.cs
*Issue #:* #76 #77 #75
Following issues are addressed in this PR:
- Removed check to validate `CognitoSessionTokens` which checks `ExpirationTime` for REFRESH_TOKEN Auth Flow.
- Fixed an issue where IssuedTime and ExpirationTime for `CognitoUserSession` object should be in UTC when it is instantiated manually by user.
___
> Fixed issues for Refresh Token auth flow.

- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/MfaAuthenticationTests.cs
Recent changes for Cognito pipeline reported test failures.
Fixed the following tests for failures:
- **Amazon.Extensions.CognitoAuthentication.IntegrationTests.MfaAuthenticationTests.TestMfaAuthenticationFlow**: Sometimes, the user pool creation was giving `Role does not have permission to publish with SNS` exception. This needs to be included in buffer exceptions.
- **CognitoAuthentication.IntegrationTests.NET45.CognitoCredentialsTests.TestGetCognitoAWSCredentials**: Intermittent issue fixed by increasing the timeout. Also, the test was not able to cleanup resources due to use of `await` and not waiting for cleanup to complete. As a result of this, there were left over user pools, roles and identity pools. Fixed the cleanup process to …
> Increased timeout for intermittent test failure and fixed cleanup process

- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
The current implementation of `CognitoUser.RespondToCustomAuthAsync` does not support setting the `ClientMetadata` property of the `RespondToAuthChallengeRequest` object, despite it [being supported by the API](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#API_RespondToAuthChallenge_RequestSyntax).
This PR rectifies this by adding a `ClientMetadata` dictionary property to the `RespondToCustomChallengeRequest` dto, which is then used in building the `RespondToAuthChallengeRequest` object.
The new property added to the `RespondToCustomChallengeRequest` dto is using an object initialiser to ensure backwards compatibility. Without it, consumers upgrading to a version of this package containing this change will experience an …
> Allow CognitoUser.RespondToCustomAuthAsync to include ClientMetadata

- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
Adds `ClientMetadata` to the SRP flow. This enables [Cognito Lambda Triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) to have access to the `ClientMetadata`.
> Add ClientMetadata to SRP auth flow

- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
Description of changes:
The issue is related to the https://github.com/aws/aws-aspnet-cognito-identity-provider package when used with a custom ApplicationUser class inherited from CognitoUser. The problem is that CognitoUserStore<TUser> in methods FindByEmailAsync and FindByIdAsync use CognitoUserPool to get the user and then tries to upcast this instance which obviously leads to the user being null.
Adding virtual modifiers will allow changing the implementation of CognitoUserPool methods to return custom own instances.
I understand that I can create a new inherited from CognitoUserStore implementation of the store to override these 2 methods with a custom CognitoUserPool, but this PR will reduce this boilerplate code.
By submitting this pull request, I confirm that my contribution is …
> Added support for generic CognitoUser in CognitoUserPool

- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
*Issue #, #79
The custom authentication flow can be used with standard SRP password verification. The initial challenge is done using SRP and the custom authentication can provide MFA challenge such as email.
More information on this can be found here.
https://aws.amazon.com/blogs/mobile/extending-amazon-cognito-with-email-otp-for-2fa-using-amazon-ses/
Allows the InitiateSrpAuthRequest to work with the custom authentication flow.
> Allow CUSTOM_AUTH authentication flow via SRP password verification

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs
*Issue #107*
https://github.com/aws/aws-sdk-net-extensions-cognito/issues/107
This PR adds caching to the AssemblyFileVersion using System.Runtime.Caching to prevent making a call to fetch the assembly everytime
> Add Caching to GetAssemblyFileVersion

- src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
*Issue #113*
*Description of changes: adds uses optional CancellationToken arguments to async methods, and passes these tokens to child tasks*
> Add optional CancellationToken arguments to async methods

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
*Issue #, if available:* #119
*Description of changes:* PR #115 added cancellation tokens with defaults, but this breaks existing callers who do not recompile.
This adds back the previous signatures, calling into the new ones with a `default` token.
I built locally with this added to the csproj, no new errors (outside of the expected one due to the snk difference):
```
<EnablePackageValidation>true</EnablePackageValidation>
<PackageValidationBaselineVersion>2.4.0</PackageValidationBaselineVersion>
```
You can view the diff from 2.4.0 to 2.4.2 at https://github.com/aws/aws-sdk-net-extensions-cognito/compare/4e9f2fa...1f63d79?diff=split
> fix: Restore public method signatures that do not take a cancellation token

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationCreateUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/MfaAuthenticationTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/SessionTests.cs
https://github.com/aws/aws-sdk-net-extensions-cognito/issues/129
Fixed bug with StartWithSrpAuthAsync(InitiateSrpAuthRequest) that would result in a deadlock scenario if the method was called by a synchronous context (e.g. .Result called on the method).
> #129 - Fix StartWithSrpAuthAsync called by Sync context

- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
Hello everyone!
I want to change order of initialization of SecretHash property in CognitoUser ctor. If i pass valid username to CognitoUser ctor, it will be ignored because of order of assignment. My changes helps create SecretHash in ctor if valid username provided. It fixes issue, when i create CognitoUser with valid username and call StartWithRefreshTokenAuthAsync. It fails because UserId used instead of Username for SecretHash calculation.
Username changes only in two palces: [CognitoUser ctor](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/143cdfbea86a9ef4e77eec5590685a0999e7000f/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L132C16-L132C16) and [UpdateUsernameAndSecretHash](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/143cdfbea86a9ef4e77eec5590 …
> CognitoUser.SecretHash initialization fix

- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
Hello. I add explicit check for DEVICE_SRP_AUTH challenge name in StartWithSrpAuthAsync method. It fix issue, when cognito return SOFTWARE_TOKEN_MFA challenge and reqeust parameter initialized with valid device properties.
I change order of parameters in some exceptions ctors(param name and message has wrong positions); use nameof() instead of parameter name as string; request parameter validation to RespondToMfaAuthAsync method.
> ChallengeName check and small improvements

- src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs
1. Replace parameter name as string to **nameof** usage, fix parameters order in several calls.
2. Remove redundant bracers at method calls.
3. Method comment: parameter name fix, add missing </param> tag, fix description for return type.
> Code improvements

- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
* The Integration test `TestGetCognitoAWSCredentials` started to fail because of change in IAM which requires any role created or modified that targets Cognito to contain a condition block. This PR adds a condition block that references the created identity pool ID.
> fix: Integration test started to fail because of missing condition block

- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/SessionTests.cs
Currently, The `TestGetUserDetails` asserts that the `UserAttributes` on index 2 matches an expected value but results in a test failure. I changed the condition so that it loops through different entries and looks for a match to the expected value.
**Note:** This test also failed without the UA changes made in this repo.
> Fix integration test

- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
ClientMetadata is set on InitiateAuthRequest if present in InitiateSrpAuthRequest. 
We use a pre-auth hook to do some captcha stuff in Cognito, we use ClientMetadata to send captcha values. 
Without this change ClientMetadata values are not send as expected. In other Client libraries (like React) this data is currently forwarded.
My pre-auth hook is now happy, but I suspect this may want a deeper look into where else these values are not added when they should be. 
> Adding ClientMetadata to InitiateAuthRequest during StartWithSrpAuthAsync

- .autover/autover.json
- .github/workflows/aws-ci.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/sync-main-dev.yml
- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- buildtools/ci.buildspec.yml
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationConfirmUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationCreateUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationSignUpUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/MfaAuthenticationTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/SessionTests.cs
- test/Amazon.Extensions.CognitoAuthentication.UnitTests/Amazon.Extensions.CognitoAuthentication.UnitTests.csproj
- test/Amazon.Extensions.CognitoAuthentication.UnitTests/BigIntegerExtensionsTests.cs
> Merge `dev` into `master`

- .autover/changes/b6c50c7c-b34d-45ef-8985-2cac2dd8e61f.json
- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
- src/Amazon.Extensions.CognitoAuthentication/Properties/AssemblyInfo.cs
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/SessionTests.cs
DOTNET-7759
* Added .NET 8 target framework and marked as trimmable
* Updated the .NET SDK dependencies to the latest version 4.0.0-preview.4
* Add SourceLink support
> feat: add support for .NET SDK V4
