- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
*Issue #, if available:* DOTNET-3202
*Description of changes:* Enabling metrics through user agent
> Enabling metrics through user agent

- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserPool.cs
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs
*Issue #, if available:* DOTNET-3202
*Description of changes:* Fixing a bug ending in redundant metrics
> Fixing a bug ending in redundant metrics

- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
*Description of changes:* Exposing a public constructor for AuthFlowResponse
> Exposing a public constructor for AuthFlowResponse

- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests.Xamarin/Xamarin.UWP/Amazon.Extensions.CognitoAuthentication.IntegrationTests.Xamarin.UWP.csproj
*Description of changes:* Bumping UWP dependency version number
> Bumping UWP dependency version number

- src/Amazon.Extensions.CognitoAuthentication/Properties/AssemblyInfo.cs
Switching AssemblyVersion to 1.0 before GA
> Switching AssemblyVersion to 1.0 before GA

- README.md
*Description of changes:* Adding NuGet link for GA
> Adding NuGet link for GA

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
*Description of changes:* Bumping up dependencies version number to 3.3.100 and updating license
> Bumping up dependencies version number to 3.3.100 and updating license

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
Update the version of Amazon.Extensions.CognitoAuthentication due to recent changes
> Update version to 2.0.1

- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
Modified retry on `TestGetCognitoAWSCredentials` to allow for any exception.
> fix: retry integration test on all exceptions

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
Version bump to 2.2.3 for release.
___
> Version bump to 2.2.3

- README.md
*Issue #, if available:* https://github.com/aws/aws-sdk-net-extensions-cognito/issues/85
*Description of changes:* Update documentation for REFRESH_TOKEN_AUTH flow to mention device tracking.
> doc: Update docs to mention device tracking in REFRESH_TOKEN_AUTH flow

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
Version bump commit to release PR https://github.com/aws/aws-sdk-net-extensions-cognito/pull/90.
___
> Version bump to 2.2.4

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
*Issue #, if available:* #106
Added new `ListDevicesV2Async` method and obsoleted `ListDevicesAsync` method in `CognitoUser` class.
___
> Added new ListDevicesV2Async method and obsoleted ListDevicesAsync method in CognitoUser class.

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
*Issue #, if available:* #113
Version bump commit to release PR https://github.com/aws/aws-sdk-net-extensions-cognito/pull/115.
___
> Version bump to 2.4.1 for releasing PR #115

- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
Add methods for software MFA setup via authorized Cognito user.
> Software MFA

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
Version bump commit to release the following PRs:
* https://github.com/aws/aws-sdk-net-extensions-cognito/pull/132
* https://github.com/aws/aws-sdk-net-extensions-cognito/pull/127
* https://github.com/aws/aws-sdk-net-extensions-cognito/pull/126
> Version bump to 2.5.2

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- src/Amazon.Extensions.CognitoAuthentication/Properties/AssemblyInfo.cs
- src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
SDK-169882
chore: Update User-Agent string
*Testing*
Verified that the UA string is `lib/AWSDotNetCognito#2.5.3.0` (based on the updated assembly file version)
> [UA update] chore: Update User-Agent string

- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
PR to version bump this PR:
* https://github.com/aws/aws-sdk-net-extensions-cognito/pull/135
> Version bump to 2.5.4

- CHANGELOG.md
> Changelog update for 2.5.4

- .github/workflows/aws-ci.yml
- buildtools/ci.buildspec.yml
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationConfirmUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationCreateUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/AuthenticationSignUpUserTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/MfaAuthenticationTests.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/SessionTests.cs
- test/Amazon.Extensions.CognitoAuthentication.UnitTests/Amazon.Extensions.CognitoAuthentication.UnitTests.csproj
- test/Amazon.Extensions.CognitoAuthentication.UnitTests/BigIntegerExtensionsTests.cs
DOTNET-7759
This PR onboards the GitHub repo to the `aws-tools-ci` testing infra.
> ci: Onboard the repo to the testing infra

- CONTRIBUTING.md
Update CONTRIBUTION.md to include change files section since the repository now uses `AutoVer` for versioning and changelog creation.
> chore: update CONTRIBUTION.md to include change files section

- .github/workflows/change-file-in-pr.yml
DOTNET-7990
Sync `dev` and `v4sdk-development`
> Sync `dev` and `v4sdk-development`

- .autover/changes/b3e93aea-1d41-4baa-a1e0-06616863a5b4.json
- src/Amazon.Extensions.CognitoAuthentication/Amazon.Extensions.CognitoAuthentication.csproj
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/Amazon.Extensions.CognitoAuthentication.IntegrationTests.csproj
DOTNET-7990
Update .NET SDK dependencies to v4.0.0-preview8
> chore: Update .NET SDK dependencies to v4.0.0-preview8

- CHANGELOG.md
- src/Amazon.Extensions.CognitoAuthentication/CognitoAuthenticationClasses.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs
- src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs
- test/Amazon.Extensions.CognitoAuthentication.IntegrationTests/CognitoAWSCredentialsTests.cs
> Sync up V3 and V4 branches
